version: 2

macros:
  - name: get_day_of_week
    description: Simply yields a "day_of_week" (Monday, Tuesday, etc) from a timestamp. Uses DuckDB's datepart function.
    arguments:
      - name: timestamp
        type: timestamp
        description: The timestamp that you want to extract day_of_week from. 
  - name: composite_key_join_conditions
    description: "{{doc('composite_key_join')}}"
    arguments:
      - name: table_1
        type: reference
        description: First table part of the join
      - name: table_2
        type: reference
        description: Second table part of the join
      - name: keys
        type: list
        description: The columns that you want to join the tables on. 
  - name: apply_multipliers
    description: "{{doc('apply_multipliers')}}"
    arguments: 
      - name: column_name
        type: string
        description: The column (must be of numeric data type) that you want to apply the multipliers to 
  - name: hourly_ridership_columns
    description: "{{doc('hourly_ridership_columns')}}"
  - name: origin_destination_columns
    description: "{{doc('origin_destination_columns')}}"
  - name: union_tables
    description: "{{doc('union_tables')}}"
    arguments:
      - name: table_name
        type: string
        description: The prefix of the table name that you want to join together (without the final suffix of a number)
      - name: columns_macro
        type: macro
        description: The particular columns that you want in each part of the UNION
      - name: num_tables
        type: integer
        description: The amount of tables that are a part of the union